"""Public interface for meshmonitor-api-client."""

from importlib.metadata import version

from .client import MeshMonitorClient
from .exceptions import (
    MeshMonitorAuthenticationError,
    MeshMonitorConnectionError,
    MeshMonitorError,
    MeshMonitorNotFoundError,
    MeshMonitorPermissionError,
    MeshMonitorRateLimitError,
    MeshMonitorResponseError,
    MeshMonitorServerError,
    MeshMonitorTransmitDisabledError,
)
from .models import (
    AutomationDefinition,
    AutomationRun,
    Capabilities,
    Channel,
    LinkQualityPoint,
    NeighborLink,
    NetworkSummary,
    Node,
    NodeDeleteResult,
    PositionFix,
    PositionHistoryPage,
    ReticulumConversation,
    ReticulumDestination,
    ReticulumIdentity,
    ReticulumInterface,
    ReticulumMessage,
    ReticulumPath,
    ReticulumSnapshot,
    ReticulumStatus,
    SendResult,
    ServerHealth,
    Source,
    SourceSnapshot,
    SourceStatus,
    TelemetryPoint,
    TelemetryRecord,
    Topology,
    TopologyEdge,
    TopologyNode,
    Traceroute,
    UnifiedMessage,
    VersionCheck,
)

__version__ = version("meshmonitor-api-client")

__all__ = [
    "AutomationDefinition",
    "AutomationRun",
    "Capabilities",
    "Channel",
    "LinkQualityPoint",
    "MeshMonitorAuthenticationError",
    "MeshMonitorClient",
    "MeshMonitorConnectionError",
    "MeshMonitorError",
    "MeshMonitorNotFoundError",
    "MeshMonitorPermissionError",
    "MeshMonitorRateLimitError",
    "MeshMonitorResponseError",
    "MeshMonitorServerError",
    "MeshMonitorTransmitDisabledError",
    "NeighborLink",
    "NetworkSummary",
    "Node",
    "NodeDeleteResult",
    "PositionFix",
    "PositionHistoryPage",
    "ReticulumConversation",
    "ReticulumDestination",
    "ReticulumIdentity",
    "ReticulumInterface",
    "ReticulumMessage",
    "ReticulumPath",
    "ReticulumSnapshot",
    "ReticulumStatus",
    "SendResult",
    "ServerHealth",
    "Source",
    "SourceSnapshot",
    "SourceStatus",
    "TelemetryPoint",
    "TelemetryRecord",
    "Topology",
    "TopologyEdge",
    "TopologyNode",
    "Traceroute",
    "UnifiedMessage",
    "VersionCheck",
    "__version__",
]
